### ISSUE TITLE
Django REST Authorization Grant Type

### ISSUE THREAD

**Issue by H0neyBadger** [evonove/django-oauth-toolkit#184]
Hello, 
I would like to provide API for both users and service accounts.
I tried to use authorization-code, but it seems not to be possible with services accounts and automated scripts.

Which Authorization Grant Type you recommend for production REST API ?
For you, what are the best practices for authenticating oauth2 users on REST API with curl?

Thanks!

**Comment by poswald** [comment]
My understanding is that if you want to authenticate another _system_ to do things not associated with any particular user, then it is best to use `client_credentials` grant type. If you want to authenticate a user via a trusted system that you built, then use the `password` grant type where your system is providing the client id and optionally the client_secret (if the client is running on your hardware, otherwise you can't do much about keeping the client secret safe). If you want to authenticate users in a 3rd party system (where you don't want your users to be giving passwords to the 3rd party) then use the `authorization_code` grant with the whole redirection flow.
