### ISSUE TITLE
Scopes should be optional for authorization code

### ISSUE THREAD

**Issue by AgDude** [evonove/django-oauth-toolkit#200]
According to: http://tools.ietf.org/html/rfc6749#section-4.1.1, scope should be optional. It appears that currently the scope parameter is required by django-oauth-toolkit.

Clearly if scopes is made optional, #195 needs to be addressed also. In many cases this may be defined at the application level.

**Comment by honestbleeps** [comment]
I'm not a project administrator, but I'm interested in helping django-oauth-toolkit be spec compliant as I'm using it on a project I work on.

It's not clear from the linked specification what scope(s), if any, should be given to the access token if the scope parameter is not provided. Do you have any thoughts on that or firm knowledge of what expected behavior is?

**Comment by synasius** [comment]
Hi @AgDude 

scopes parameter is optional on the authorization request and DOT is compliant with that.

On the contrary, scopes should always be provided in the access token response also they are missing from the auth request. Please read: http://tools.ietf.org/html/rfc6749#section-3.3

**Comment by outsbart** [comment]
Fixed in #333
