### ISSUE TITLE
Add support for django 1.8

### ISSUE THREAD

**Issue by masci** [evonove/django-oauth-toolkit#223]
Drop support for 1.6, keep for 1.4 until next October instead.

**Comment by robustican** [comment]
+1.  Looking forward to this working in 1.8.  any estimates on the 0.9.0 release?

**Comment by glynjackson** [comment]
Can any one tell me what is not working on Django 1.8? I installed repo version with version 1.8 and it appears to be working fine (only tested token auth).

**Comment by synasius** [comment]
Hi @glynjackson 
DOT works with django 1.8 but we need to added it to our test matrix. Also some tests needs to be fixed to run. So, it works but it's not officially supported, but if you want to use it along wiht django 1.8 it's fine :)

Also, if you're using a custom application model, please be sure to check #227

**Comment by glynjackson** [comment]
Nice work thank you! Also thanks for the link to custom app model, may have just saved me a few headaches :+1:

**Comment by honestbleeps** [comment]
just to add to this on django 1.8 support:

Django 1.8 doesn't allow "fields" to be specified at the same time as "form_class" -- this caused me some problems when overriding the ApplicationUpdate form, because there's a mixin that sets fields = "__all__"

I'm not sure what the right "django way of doing things" is to get around this - but I ultimately put fields = None and form_class = MyFormClass into my view file, rather than passing the form class to as_view() in my urls.py and that fixed the issue.

It's worth noting this might be the sort of thing that should go in the documentation, but I feel sort of like I hacked/slashed my way to a fix and I'm not sure it's the one I'd prescribe. I'm still relatively new to Django with just a few months experience on it.

**Comment by masci** [comment]
@honestbleeps did you try passing both

**Comment by kevin-brown** [comment]
I've been testing recently with 1.8 and nothing has come crashing down (yet), but I did want to make one note.

Django, since 1.7, has supported custom `AppConfig` options for each package which allows you to [give a custom label](https://docs.djangoproject.com/en/1.8/ref/applications/#django.apps.AppConfig.verbose_name) to applications in the admin panel.

So instead of the admin panel looking like

![How the admin panel currently looks](https://i.imgur.com/oCb8dKh.png)

It could look like

![How it looks with a changed app label](https://i.imgur.com/XIwu65N.png)

Which would avoid any possible confusion with [Django OAuth2 Provider](django-oauth2-provider).
