### ISSUE TITLE
Bad migration in 0.8.0 - created AccessToken.user_id is not null

### ISSUE THREAD

**Issue by shamanis** [evonove/django-oauth-toolkit#284]
Version: 0.8.0
Why in the model AccessToken is defined user = models.ForeignKey(AUTH_USER_MODEL, blank=True, null=True) but it is created in the database user_id not null?
Migration 0001_initial:
('user', self.gf('django.db.models.fields.related.ForeignKey')(to=orm["%s.%s" % (User._meta.app_label, User._meta.object_name)]))
Because of this I have not worked client-credential authentication. It gives an error message "column user_id can not be NULL"
Backend PostgreSQL 9.4

**Comment by poswald** [comment]
Users are nullable as of #357 (see the original discussion in #38). I still personally recommend creating `User` objects for client-credentials requests because libs like DRF and Django core assume all requests are tied to a "user" but the no longer have to be the one associated with an `Application` object which can now be null.
