### ISSUE TITLE
Why do we need SessionAuthenticationMiddleware for DOT??

### ISSUE THREAD

**Issue by lzen** [evonove/django-oauth-toolkit#295]
In the tutorial part 3 (https://django-oauth-toolkit.readthedocs.org/en/latest/tutorial/tutorial_03.html), it is mentioned that SessionAuthenticationMiddleware should be placed before OAuth2TokenMiddleware. I understand if one uses SessionAuthenticationMiddleware in the code it should be before OAuth2TokenMiddleware, but what the wording in the tutorial also means to me that SessionAuthenticationMiddleware is required for DOT. Is that true?? If not, I can change the wording to make it clear. Thanks!

**Comment by lzen** [comment]
@masci Hi Massimiliano, would you please take a look? Thank you!

**Comment by masci** [comment]
Hi @lzen 
the docs in that part are definitely broken in several points. `SessionAuthenticationMiddleware` is not required, I don't even know why it's there, likely a copy&paste fail.

I would remove the part 
> only pay attention to the order in which Django processes authentication backends.

because yes, it's important, but it's confusing for the following paragraph about the middleware, for which the relative docstring contains a clear and correct documentation, see:
https://github.com/evonove/django-oauth-toolkit/blob/master/oauth2_provider/middleware.py#L9

Thanks for reporting and if you want to provide a patch to address this issue I won't stop you :)

**Comment by lzen** [comment]
Hi @masci 
Thanks for the quick confirmation! Yes I'll fix the doc with a PR now :)

FYI this was added in https://github.com/evonove/django-oauth-toolkit/issues/152, but I'll make it clear in the doc that they should be in this order "if you use SessionAuthenticationMiddleware in the project".

**Comment by lzen** [comment]
PR created. Thank you @masci !
