### ISSUE TITLE
Can i user /o/token url anyway to login via 2 parameters

### ISSUE THREAD

**Issue by mascot6699** [evonove/django-oauth-toolkit#339]
I know we need the username and password along with client secret and client id  to login but I wanna login using email/phone_number(both are fields of user table i have. I can only set one of them as username so still have a problem as i need to login any among them.)

One way i thought of is add my own api and authenticate the user and then i could use /o/token to generate token by calling it internally. 

Is there any obvious way that i might be missing?

**Comment by Gr1N** [comment]
Due to RFC 6749 using the resource owner password credentials grant type you can not login using email or phone number or anything else. 

To my mind you need to create custom (https://tools.ietf.org/html/rfc6749#section-4.5) grant type with set of fields which you want to use (e.g. email or phone number).

**Comment by mascot6699** [comment]
Thanks for now I have done as I suggested above I will have a look at this in weekends. Also you may close this issue.

**Comment by elcolie** [comment]
@mascot6699 What have you done so far?
I am facing the same issue.
