### ISSUE TITLE
AccessToken matching query does not exist in /auth/token

### ISSUE THREAD

**Issue by maticomp** [evonove/django-oauth-toolkit#350]
We've lately started seeing strange behaviour when requesting new `access_token` using `refresh_token` grant.

The POST data to `/auth/token` (which is a standard `oauth2_provider.views.TokenView` view) as follows:

```
{
    'client_id': 'testclient',
    'client_secret': 'testclient',
    'grant_type': 'refresh_token',
    'refresh_token': 'RTLA9gRZSl07cDZIKdAZSRFqih5u5u'
}
```

yields `AccessToken matching query does not exist.` in `oauth2_provider/models.py` in `RefreshToken.revoke` in `AccessToken.objects.get(id=self.access_token.id).revoke()`.

At any given time all refresh tokens in database have corresponding access tokens to them. 

Nothing has been changed for the past 4 months in the stack and we've started seeing this problem only today. I'm scratching my head why such an error would occur there. I'd be very grateful for any ideas what could be going on :)

**Comment by poswald** [comment]
Did this stop happening to you? My guess - based purely on the date you raised this - is that there is a bug in the `clear_expired` function or something such that the `timezone.now` and the `REFRESH_TOKEN_EXPIRE_SECONDS` function don't work well with the leap year date in Feb.

**Comment by maticomp** [comment]
Yes and no. Over the weekend developers of mobile application that used our API found the error on their end, but I think it still shouldn't behave like that.

They had a race condition causing two simultaneous requests for token refresh using the same refresh token and that, as a cause of this error, is easily reproductible. The server using django-oauth-toolkit is running on gunicorn with several workers.

In addition to the error mentioned above, the same approach sometimes causes another error here:

`
/.../env/lib/python3.4/site-packages/oauth2_provider/oauth2_validators.py in save_bearer_token
                            assert()  # TODO though being here would be very strange, at least log the error
`

Cheers!

**Comment by vladlep** [comment]
Hi I have experienced the same error. 
After going over the code for a while I realized that when using a refresh token to generate new access&refresh tokens, at the end the existing tokens for that users are deleted **at the end**. This is done on the `class RefreshToken(models.Model)` in the `revoke` method.

So, the problem could be, from my understanding, that when you make 2 calls in parallel, both could pass the initial validations (the refresh tokens are correct), both proceed to create new refresh and access tokens but only 1 can delete the old database entries while the second one generates an error.

I think there could be 2 solutions to this:

1. on the  oauth library, in case the revoke methods on the RefreshToken model (or the one on the AccessToken model) fail to delete the tokens, the call should return a failed request status( 400 or 401 i guess?)

2. the client(mobile) does not do parallel request to refresh the token

For the first option I think the change is not that hard actually. In the `oauth2_validators.py` right now we have these lines: 

    def save_bearer_token(self, token, request, *args, **kwargs):
        """
        Save access and refresh token, If refresh token is issued, remove old refresh tokens as
        in rfc:`6`
        """
        if request.refresh_token:
            # remove used refresh token
            try:
                RefreshToken.objects.get(token=request.refresh_token).revoke()
            except RefreshToken.DoesNotExist:
                assert()  # TODO though being here would be very strange, at least log the error


If they are extended  to somethings like:

    try:
        RefreshToken.objects.get(token=request.refresh_token).revoke()
    except (RefreshToken.DoesNotExist, AccessToken.DoesNotExist):
                #TODO: cause method to fail and catch the exception somewhere higher to report it to the user.


Does this makes sense? I am also very interested if this issue is fixed. 

Vlad

**Comment by pySilver** [comment]
@vladlep take a look at my comment here #304 it works for us on production environment and all problems gone. I suggest someone make a PR out of my comment (sorry, I'm totally out of time)

**Comment by vladlep** [comment]
Thanks, your comment it is very useful. Right now I do not have the time either to fix it, working at a startup and time feels always an issue. I will just hack around it. 

It makes a lot of sense that you made the method atomic. 
But from what i can see you are now never revoking(deleting) the access or refresh tokens anymore. In my personal opinion they should be deleted at some point if they will not be used anyways, to keep the table small.

**Comment by pySilver** [comment]
@vladlep since there is a management command built-in, some periodic task cleans up expired tokens for me. Trust me – this is the only way to fix concurrent issue here :)

**Comment by synasius** [comment]
#389 merged
