### ISSUE TITLE
How to use this library with mobile 

### ISSUE THREAD

**Issue by sandeshnaroju** [evonove/django-oauth-toolkit#418]
I am working on android project. All my users install apps and provide phonenumbers to get client ID and client secret as part of registration process. And get access token to further use whole resources. I am using django restframework I have searched a lot in google to find how to do it for mobile users. Django Oath2 toolkit provides documentation in which it shows minimal setup with templateview to manually provide details to get credentials for logged in user in browser. But I need to generate credentials dynamically for mobile users. I want to generate in views.py dynamically when user provide their phonenumber. How to do that? Any small example or hint?

**Comment by poswald** [comment]
This might be a better question to ask in the mailing list since the issue tracker is for tracking code issues.

I'm not familiar with doing it dynamically but as a hint my guess is that you would want to use OAuth2 with Resource Owner Password Credentials Grant. Others on the mailing list might have more experience and better ideas about this.
