### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by clintonb** [evonove/django-oauth-toolkit#482]
Nearly four months have progressed since the release of 0.12.0. In that time numerous features have been added to this library that would be quite useful. Please create a new release, and publish to PyPI.

Answering before the question is asked...why not use a commit from GitHub? Caching. `pip` does not cache installations from GitHub. `pip` must download the entire repository every time `pip install` is run against a requirements file with a Git-sourced package.

**Comment by clintonb** [comment]
FYI @jleclanche @synasius

**Comment by phillbaker** [comment]
@clintonb I think we can lock down pip to a specific commit and that _is_ cached, but I'm having trouble with that.

It seems like `pip` is having trouble with the egg information, because the `oauth2_provider` directory is different than the package name of `django-oauth-toolkit`. In my `requirements.txt` currently:

```
-e git+https://github.com/evonove/django-oauth-toolkit.git@643c3d0c8dd0f8b05f523902d1375b3b8d621e31#egg=django-oauth-toolkit
```

Which prints:
```
  Running setup.py (path:.../src/django-oauth-toolkit/setup.py) egg_info for package django-oauth-toolkit produced metadata for project name unknown. Fix your #egg=django-oauth-toolkit fragments.
```

This also doesn't install the dependencies, although it does not error out. Using pip 9.0.1 with python 3.4. How are you installing from github?

Sorry for the semi-related question - I can open a separate question if that'd help.

**Comment by clintonb** [comment]
@phillbaker thanks for the input. Besides the release, I'm mostly looking to get some input from the maintainers. Think of this as a litmus test. This is our second OAuth library for edX. If we can't get some form of commitment from maintainers, we will need to look for yet another library or consider forking/maintaining our own (which is not desired).

**Comment by jleclanche** [comment]
@clintonb yes I already sent an email to @synasius yesterday asking for a 0.13 or 1.0 release. I agree we're ready fo rit.

**Comment by jleclanche** [comment]
Django Oauth Toolkit 1.0 is out.

**Comment by clintonb** [comment]
Thanks, and congratulations on reaching 1.0!!!
