### ISSUE TITLE
Custom oauth in django website

### ISSUE THREAD

**Issue by amitmoralwar** [evonove/django-oauth-toolkit#565]
I have a django website. I installed and configure django-oauth-tolkit. I have another website where my users resides. I want to give access of my django website to those users of another website using django-oauth-toolkit. I searched on the internet and I get authentication with gmail,facebook,github,twitter
etc, I want similar kind of thing but instead of gmail and facebook I want to use my site for authentication.
If anyone has any idea about it would be very helpful to proceed me further.

**Comment by jleclanche** [comment]
You should go through some documentation on OAuth2. This especially: https://aaronparecki.com/oauth-2-simplified/ // https://oauth.net/2/

What you want is an "accounts" website (either your primary website or a dedicated login service), which implements an oauth2 provider api.

Two caveats:

1. Make sure this is actually what you want, which is why I encourage you to read documentation on oauth2. Decentralized authentication across platforms you own is great, if it makes sense to do at your scale. It often doesn't for small projects where you can instead share an *authentication (users) database* and have SQL be your API.

2. Your question is too high level to answer, and not really in scope for this issue tracker. What I recommend is go through enough of the documentation I linked to understand what you actually want to do and how to structure it, then see how that can be implemented using DOT. The hard part really is just familiarizing yourself with OAuth2 concepts and how they work, once that's done, the rest is easy.
